<%@ include file="/WEB-INF/jsp/include/tags.jsp" %>

<stripes:layout-render name="/WEB-INF/jsp/layout/pub/layout.jsp" pageTitle="Privacy Policy">
    <stripes:layout-component name="contents">
        <div class="zion-general-page">
            <div class="page-header">
                <h1>Privacy Policy</h1>
            </div>
	        <article>
	            <p>
					The following Privacy Policy discloses our information-gathering and dissemination practices for our website located at STYLEHUB (the "Site"), our services and the STYLEHUB mobile applications (collectively, the "Service"). By using the Service, you hereby warrant and represent that you have read, understand and agree to all terms and conditions stated herein, including our Terms of Use, available at terms, which is incorporated herein by reference and govern the use of the Service offered by STYLEHUB, and that you are giving STYLEHUB permission to use and store such information consistent with this Privacy Policy and our Terms of Use. A user of the Service is hereinafter referred to as a "User," or collectively, the "Users".
	            </p>
	            <h2>LINKS AND INFORMATION</h2>
	            <p>
					The Service contains links to other websites. Please see the "Links to Other Websites" section of our<a href="<c:url value="/termsandcondition"/>"> Terms of Use</a>.
	             </p>
	             <h2>INFORMATION RECEIVED BY STYLEHUB</h2>
	             <p>
	                Personal Information. STYLEHUB collects personal information only if you voluntarily choose to share such information with STYLEHUB. You may browse the Site without disclosing any personal information. However, in order for you to use certain features and functionality of the Service, we may require that you furnish personal information. When you register your account, sign up for newsletters, complete forms for optional programs, surveys, contests and other entries, and through communications transmitted through STYLEHUB, applications and your use of the STYLEHUB mobile application, we collect information including your name, address, phone number, age and email address. You also may choose to send STYLEHUB personally identifying information in an email message containing information or inquiries about the Service. 
	             </p>
	             <p>
	               Anonymous or Aggregated Data. STYLEHUB collects and stores certain data about the use of the Service on an aggregate and/or anonymous basis. STYLEHUB does not link this information to anything personally identifiable to you.
	             </p>
	             <p>
					 Cookies and Other Technologies. When you visit websites on the Internet, your browser may automatically transmit information to the websites during every visit. Like many websites, we may use "cookies" to collect information. A cookie is a small data file that we transfer to your computer's hard disk for record-keeping purposes. We may utilize persistent cookies that only STYLEHUB can read and use to save your login information for future logins to the Service, to hold session information, and to track user preferences. We may utilize session ID cookies to enable certain features of the Service, to better understand how you interact with the Site and to monitor aggregate usage by our Users and web traffic routing on the Service, and to identify visited areas of the Site and Service. Unlike persistent cookies, session cookies are deleted from your computer when you log off from the Site and Service and then close your browser. Third party advertisers on the Site may also place or read cookies on your browser and we may use Flash cookies (or local shared objects) to store your preferences or display content based upon what you view on our site to personalize your visit. You can instruct your browser, by changing its options, to stop accepting cookies or to prompt you before accepting a cookie from the websites you visit. If you do not accept cookies, however, you will not be able to use all portions or all functionalities of the Service. We and our service providers may also use "pixel tags," "web beacons," "clear GIFs," or similar means in connection with the Service and HTML-formatted email messages to, among other things, track the actions of Users and email recipients, to determine the success of marketing campaigns and to compile aggregate statistics about Site usage and response rates. We may also engage one or more third party service providers to serve online advertisements on our behalf. They may use a "pixel tag" to collect anonymous information about your visits to the Site and to other websites, and they may use that information to target advertisements for goods and services. This information is collected anonymously, in a manner that does not personally identify you.
	             </p>
	             <p>
	               IP Address. When you visit and interact with the Site, STYLEHUB and/or third parties with whom STYLEHUB has contracted to provide services to STYLEHUB may collect your Internet Protocol Address ("IP Address"), which is a number that is automatically assigned to the computer that you are using by your Internet Service Provider. This number is identified and logged automatically in our server log files whenever you visit the Site, along with the time(s) of your visit(s) and the page(s) that you visited. We use IP Addresses to monitor the regions from which Users navigate the Site and for fraud prevention purposes.
	             </p>
	             <p>
	               Employee Data. STYLEHUB also collects and uses personal data regarding its employees ("Employee Data"), which may include: name, address, job title and other job information, location, compensation information, identification number, employment history, and a copy of employment agreements. Only authorized STYLEHUB staff have access to your personal information in its entirety. Other staff may have access to portions of this information if it pertains to their job duties.
	             </p>
	             <h2>STYLEHUB'S USE OF PERSONAL INFORMATION</h2>
	             <p>STYLEHUB uses personal information for the following general purposes: to provide our products and the Service (including, for example, to facilitate payments), to analyze Site usage and improve our products and the Service, to contact you and deliver administrative notices and communications relevant to your use of our products and Service, for internal market research, troubleshooting problems, and detecting and protecting against error, fraud or other criminal activity, for distribution to third-party contractors that provide services to STYLEHUB and partners of STYLEHUB who are bound by privacy restrictions at least as restrictive as those set forth in this Privacy Policy and to enforce our Terms of Use. Although we ensure that our third party contractors receiving your information are bound by privacy restrictions at least as restrictive as those set forth in this Privacy Policy, STYLEHUB is not responsible for any issues that may arise regarding the privacy policies of any of its providers, affiliates or advertisers. By using the Site, you do hereby agree to hold STYLEHUB harmless from any claims and/or damages that may arise from the actions of any of its providers, affiliates, and/or advertisers. STYLEHUB's decisions regarding the use of information collected from Users are driven by two factors: (1) improving user experience by offering personalized services, content and advertising, and (2) market research. Ads are a standard part of user experience on the Internet, and STYLEHUB believes that targeted advertising enhances this experience. STYLEHUB may use cookies and other technologies and personal information to place ads where they believe interested parties will see them. In addition to ads displayed via the Service, STYLEHUB may advertise products, companies and events that the Company may think interests users through the email addresses provided. STYLEHUB may analyze personal information and web navigational data based on user interests and may use analyses from this information in a way that doesn't reveal a User's personal information ("Market Research") in order to: (1) market the Service, and (2) increase the likelihood that a group's experience with the Service is relevant to its interests as a whole. STYLEHUB uses data at the individual level to display products and services to Users who express an interest in these products and services, through a poll for example, or to Users who can be presumed to have an interest based on results from Market Research. Employee Data is only used for the purposes of facilitating the performance of certain administrative tasks and functions relating to general employment and for processing and investigating reports under STYLEHUB's codes and policies.</p>
	             <h2>ANALYTICS INFORMATION</h2>
	             <p>STYLEHUB uses third-party analytics tools to help measure traffic and usage trends for the Services. These tools collect information sent by a user's browser as part of a web page request, including the web pages users visit, browser add-ons, and other information that assists STYLEHUB in improving the Services. STYLEHUB may collect and use this information with a user's Personally Identifiable Information and stitch together session data from unauthenticated User visits with authenticated User visits to build a broader profile of individual Users to better serve users.</p>
	             <h2>CHOICE/OPT-OUT</h2>
	             <p>You may opt-out of receiving communications from STYLEHUB and our partners, remove your information from our database, and choose to not receive future communications unrelated to the Service. During registration you may have the option to choose whether to receive correspondence from either STYLEHUB or its partners and whether you want to participate in a variety of STYLEHUB programs. This information remains on your profile where you can, at any point, by using the features and functionality of the Service easily edit it to indicate that you have changed your mind. You always have the option to ask STYLEHUB not to contact you with this information again. If you receive unsolicited email from a STYLEHUB domain, please contact us at <a href="mailto:<c:out value="${appSupportEmail}"/>"><c:out value="${appSupportEmail}"/></a>.</p>
	             <h2>DO NOT TRACK</h2>
	             <p>While STYLEHUB is committed to your privacy, currently, the Service does not respond to your web browser "do not track" signals or other mechanisms. If, in the future, STYLEHUB creates a program or protocol to respond to such web browser "do not track" signals, we will inform you of the details of that protocol in this Privacy Policy.</p>
	             <h2>STYLEHUB'S INFORMATION RETENTION POLICY</h2>
	             <p>To preserve the integrity of our databases, we may retain information submitted by Users for an indefinite length of time. If required by law, we will delete personal information by erasing it from our database. We will also respond to User requests to delete or correct account or personal information, which you can do by contacting STYLEHUB at <a href="mailto:<c:out value="${appSupportEmail}"/>"><c:out value="${appSupportEmail}"/></a> or by using the features and functionality of the Service.</p>
	             <h2>STYLEHUB'S SECURITY OF COLLECTED INFORMATION</h2>
	             <p>Your STYLEHUB account is password-protected so that only you and authorized STYLEHUB staff have access to your account information. In order to maintain this protection, do not share your password with anyone. If someone contacts you and claims they are a representative of the STYLEHUB staff, and asks for any personal account information, including password, check their URL. If it doesn't say that they are from stylehub.online, then they aren't. Also, if you share a computer, be sure to sign out of your STYLEHUB account and close the browser window. This will help protect your information entered on public terminals from disclosure to third parties. STYLEHUB makes every effort to ensure that your information is secure on its system by backing up data in separate backup drives and uses public key access encryption and firewalls on both our main and backup servers. We also employ customer record managers to protect against loss, misuse and alteration of the information under our control. Extremely sensitive information is always transmitted in encrypted form. Only certain authorized STYLEHUB staff can access personal information, and only if it is relevant to their job duties. STYLEHUB's staff is dedicated to maintaining this Privacy Policy and other privacy initiatives, periodically reviewing security and making sure that every STYLEHUB employee is aware of STYLEHUB's security practices. Unfortunately, no data transmission over the Internet is 100% secure. As a result, STYLEHUB cannot guarantee the security of any information you transmit to us, and you do so at your own risk. While STYLEHUB will use commercially reasonable efforts to ensure the security of all credit card and all other personal information, we expressly disclaim any liability for any unauthorized access to or use of our secure servers and/or any and all personal and/or financial information stored therein, and you agree to hold STYLEHUB harmless for any damages that may result therefrom. If you have any further questions on this issue, please refer to the Terms of Use. STYLEHUB expressly disclaims any liability that may arise should any other individual obtain the information you submit to the Site.</p>
	             <h2>WITH WHOM DOES STYLEHUB SHARE INFORMATION?</h2>
	             <p>
	               When you submit information to STYLEHUB, it is collected, processed and maintained solely by us or by third party agents who are bound by privacy restrictions at least as restrictive as those set forth in this Privacy Policy. In addition, in order to deliver the paid Service and process your payment, we need to share information about you with payment processing partner(s) that we use to validate and charge your payment method. Only our payment processing partner(s) receive any credit card or payment information. We may allow our business partners to collect information about Users that is not extremely sensitive personal information. If you would like to opt out from the onward transfer of your information to our non-agent partners, you may send us an email at <a href="mailto:<c:out value="${appSupportEmail}"/>"><c:out value="${appSupportEmail}"/></a>. Include the word "privacy" in the subject line of the email and all your registration information in the body of the email. Some STYLEHUB content is "sponsored by" or "presented by" other companies. STYLEHUB shares market research data (how the sponsorship performed, names of contest winners, etc.) collected on the Site or via email surveys with these partners. This information is aggregate and not linked to specific Users. Partners may sponsor promotions, contests and sweepstakes that require you to reveal details such as your name, address or phone number. Always check their privacy policy before revealing information about yourself. If you don't want these sponsors to have your personal information, you can choose to not participate. STYLEHUB reserves the right to disclose personal information from both private and public areas of the Site at our discretion, if required by law or if we are given reason to believe, in our sole discretion, that someone is causing injury to or interference with the rights of Users, the general public, or STYLEHUB, to comply with a judicial proceeding, court order or legal process. We will not transfer to a non-agent third party any personal information that is sensitive in nature, such as information specifying your medical or health condition, racial or ethnic origin, political opinions, religious or philosophical beliefs, trade union membership without your prior affirmative consent. Finally, STYLEHUB reserves the right to transfer, sell and/or distribute all information collected through the Service to an affiliate, subsidiary, or third party in the event of any reorganization, merger, sale, joint venture, assignment, transfer or other disposition of all or part of our business, assets or stock. We will use our best efforts to ensure that the new entity follows this Privacy Policy with respect to your personal information, as and to the extent required by applicable law.
	             </p>
	             <h2>CHILDREN'S PRIVACY AND NOTE TO PARENTS AND GUARDIANS</h2>
	             <p>We do not knowingly collect personal information from children under 13 years of age. Our Service is not directed to children under the age of 13 and children are not permitted to use the Service. If we become aware that we have unknowingly collected personal information from a child under the age of 13, we will make commercially reasonable efforts to delete such information from our database. If you are a parent or guardian of a child under the age of 13, and you believe that your child has provided us with personal information, please contact us using the information in the "Contact Us" section at the end of the Privacy Policy.
	             </p>
	             <h2>HOW CAN USERS EDIT THEIR INFORMATION?</h2>
	             <p>STYLEHUB strongly believes in providing users with the ability to access and edit their personal information. Users may use the features and functionality of the Service to view, update, edit and correct account information by logging in with their account usernames and passwords. In an effort to protect the integrity of sensitive data, some information, such as age, cannot be altered. For example, since children under 13 are not allowed to register as Users, we need to take reasonable measures to preserve the accuracy of our Users' ages. If you need to make a change, contact us at <a href="mailto:<c:out value="${appSupportEmail}"/>"><c:out value="${appSupportEmail}"/></a>. Our databases automatically update any personal information you edit in your profile, or that you request we edit. Information transmitted through boards, chats, polls or through any other means remains in our databases and becomes the property of STYLEHUB upon submission.
	             </p>
	             <h2>NOTIFICATION OF CHANGES</h2>
	             <p>STYLEHUB's security policies and this Privacy Policy are periodically reviewed and updated as necessary. This Privacy Policy might change as STYLEHUB updates and expands the Service. STYLEHUB will make commercially reasonable efforts to notify its users of any changes to the Privacy Policy via email or through the Service, but will not be liable for any failure to do so. STYLEHUB also encourages users to review the Privacy Policy periodically. If you do not understand any of the terms or conditions of any of STYLEHUB's policies, contact STYLEHUB via email at <a href="mailto:<c:out value="${appSupportEmail}"/>"><c:out value="${appSupportEmail}"/></a>. STYLEHUB and its Service are based in the U.S., and STYLEHUB's offices are headquartered in the U.S. Please be aware that information you provide to STYLEHUB as a result of your use of the Service may be processed and transferred to the U.S. and be subject to U.S. law. The privacy and data protection laws in the U.S. may not be equivalent to such laws in your country of residence. By using the Site, participating in the Service, or by providing STYLEHUB with your information, you consent to this collection, transfer, storage, and processing of information to and in the U.S. STYLEHUB will take all steps reasonably necessary to ensure that you data is treated securely in accordance with this Privacy Policy.</p>
	             <h2>HOW CAN I REACH STYLEHUB STAFF?</h2>
	             <p>If you have technical problems, questions or other issues related to your use of STYLEHUB, please click the CONTACT link at the bottom of any page of the Site. You can also email <a href="mailto:<c:out value="${appSupportEmail}"/>"><c:out value="${appSupportEmail}"/></a>. STYLEHUB's staff will respond to all requests sent through mail or email from Users and parents interested in knowing more about what personal information is stored on the STYLEHUB database, to change or edit personal information, or have additional questions regarding privacy.</p>
	             <h2>CONTACT US</h2>
	             <p>If you have any questions about this privacy statement, the practices of this site, or your dealings with the Site, you may contact us at <a href="mailto:<c:out value="${appSupportEmail}"/>"><c:out value="${appSupportEmail}"/></a>.</p>
	        </article>
	    </div>
    </stripes:layout-component>
</stripes:layout-render>
